[package]
name = "hebrew-week"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = "0.6.20"
hyper = { version = "0.14.27", features = ["full"] }
rusqlite = { version = "0.29.0", features = ["bundled"] }
tokio = { version = "1.33.0", features = ["full"] }
tower = "0.4.13"
